// GET_COUNTRY_BY_<<ENDPOINT>>
export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
export const GET_BY_NAME = 'GET_BY_NAME';
export const GET_BY_CALLING_CODE = 'GET_BY_CALLING_CODE';
export const GET_BY_CURRENCY = 'GET_BY_CURRENCY';
export const GET_BY_REGIONAL_BLOCK = 'GET_BY_REGIONAL_REGION';
export const GET_BY_REGIONAL_REGION = 'GET_BY_REGIONAL_BLOCK';

